image: images.borgy.elementai.lan/anmol/anmol_test
command: bash -c "python /mnt/AIDATA/home/anmol/DrNet-tflow/run.py --num_gpus 4 --batch_size 16 --size_pose_embedding 5 --size_content_embedding 128 --max_steps 12 --run_name bs128 --num_epochs 1000000"
name: anmol1
reqCores: 20
reqGpus: 8
reqRamGbytes: 180
volumes:
  - /mnt/AIDATA/:/mnt/AIDATA/
  
